blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('blog/', views.index, name='index'),
    path('', views.home, name='home'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogger/<int:pk>', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='blog_comment'),
    path('blog/create', views.BlogCreate.as_view(), name='blog_create'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('polls/', include('polls.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    # path('', RedirectView.as_view(url='/blog/', permanent=True)),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models

# Create your models here.
from datetime import date
from django.urls import reverse
from django.contrib.auth.models import User

class BlogAuthor(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField()

    class Meta:
        ordering = ["user","bio"]

    def get_absolute_url(self):
        return reverse('blog:blogs-by-author', args=[str(self.id)])

    def __str__(self):
        return self.user.username


class Blog(models.Model):
    name = models.CharField(max_length=200)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    post_date = models.DateField(default=date.today)

    class Meta:
        ordering = ["-post_date"]

    def get_absolute_url(self):
        return reverse('blog:blog-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog= models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title=75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from .models import Blog, BlogAuthor, BlogComment

def index(request):
    return render(request, 'index.html')

def home(request):
    return render(request, 'home.html')

class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5

from django.shortcuts import get_object_or_404

class BlogListbyAuthorView(generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = Blog
    paginate_by = 5
    template_name ='blog/blog_list_by_author.html'

    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        target_author=get_object_or_404(BlogAuthor, pk = id)
        return Blog.objects.filter(author=target_author)

    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(BlogAuthor, pk = self.kwargs['pk'])
        return context

class BloggerListView(generic.ListView):
    model = BlogAuthor
    paginate_by = 5

class BlogDetailView(generic.DetailView):
    model = Blog


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login. 
    """
    model = BlogComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('blog:blog-detail', kwargs={'pk': self.kwargs['pk'],})

class BlogCreate(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['name', 'description']

    def get_context_data(self, **kwargs):
        context = super(BlogCreate, self).get_context_data(**kwargs)
        context['blogauthor'] = get_object_or_404(BlogAuthor, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(BlogCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog-detail', kwargs={'pk': self.kwargs['pk'],})

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice

from django.views import generic

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/__base__.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>Document</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link href="{% static 'images/favicon.ico' %}" rel="icon"/>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        {% block script %}{% endblock %}
    </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:home' %}">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'blog:index' %}">Blog
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block header %}{% endblock %}        

        <!-- Page Content -->
        <section class="py-5">
            <div class="container-fluid">
                {% block container %}{% endblock %}
            </div>
        </section>
    </body>
</html>

blog/templates/base.html
{% extends '__base__.html' %}

{% block container %}
<div class="row">
    <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
            <li><a href="{% url 'blog:index' %}">Blog Home</a></li>
            <li><a href="{% url 'blog:blogs' %}">All blogs</a></li>
            <li><a href="{% url 'blog:bloggers' %}">All bloggers</a></li>
        </ul>

        <ul class="sidebar-nav">
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'admin:logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'admin:login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
        </ul>

        {% endblock %}
    </div>
    <div class="col-sm-10" style="margin-top: 20px">
        {% block content %}{% endblock %}

        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock %}

    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p><strong>Post date</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blog:blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Description:</strong></p>
<p id='t' style="white-space:pre-wrap;">{{ blog.description }}</p>
<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog:blog_comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'admin:login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 

</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block content %}
    <h1>All blogs</h1>

    {% if blog_list %}
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}}) — <a href="{% url 'blog:blogs-by-author' blog.author.pk %}">{{ blog.author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no blogs.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blog_list_by_author.html
{% extends "base.html" %}

{% block content %}
    <h1>Blogger: {{blogger}}</h1>
    
    <h3>Bio</h3>
    
    <p>{{blogger.bio}}</p>
    
    

    {% if blog_list %}
    <h3>Blogs list</h3>
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}})</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>This blogger hasn't posted anything yet.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends 'base.html' %}

{% block content %}
<h1>All bloggers</h1>
<ul>
    {% for blogger in blogauthor_list %}
    <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger.user }}</a>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/blogcomment_form.html
{% extends "base.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog:blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/home.html
{% extends '__base__.html' %}

{% block header %}
<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <!-- Slide One - Set the background image for this slide in the line below -->
            <div class="carousel-item active" style="background-image: url('../static/images/first.jpeg')">
                <div class="carousel-caption d-none d-md-block">
                    <h2 class="display-4">First Slide</h2>
                    <p class="lead">This is a description for the first slide.</p>
                </div>
            </div>
            <!-- Slide Two - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('../static/images/second.jpeg')">
                <div class="carousel-caption d-none d-md-block">
                    <h2 class="display-4">Second Slide</h2>
                    <p class="lead">This is a description for the second slide.</p>
                </div>
            </div>
            <!-- Slide Three - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('../static/images/third.jpeg')">
                <div class="carousel-caption d-none d-md-block">
                    <h2 class="display-4">Third Slide</h2>
                    <p class="lead">This is a description for the third slide.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>
{% endblock %}        

{% block container %}
<h1 class="display-4">Full Page Image Slider</h1>
<p class="lead">The background images for the slider are set directly in the HTML using inline CSS. The images in this snippet are from <a href="https://unsplash.com">Unsplash</a>, taken by <a href="https://unsplash.com/@joannakosinska">Joanna Kosinska</a>!</p>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>DIY Blog Home</h1>

<p>Welcome to <em>DIY Blog</em>, a very basic Django blogging website developed as an <a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog">assessment task</a> for the Django learning module on the Mozilla Developer Network.</p>



<h2>UML Models</h2>
<p>An UML diagram of the site's Django model structure is shown below. </p>

<div>
    {% load static %}
    <img src="{% static "images/diy_django_mini_blog_models.png" %}" alt="My image" style="width:555px;height:540px;"/>
</div>  
{% endblock %}

polls/templates/base_polls.html
{% extends 'base.html' %}

{% block sidebar %}
<ul class="sidebar-nav">
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
{% endblock %}
</ul>

polls/templates/polls/detail.html
{% extends 'base_polls.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base_polls.html' %}

{% block content %}
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'base_polls.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}